# Generated by Django 3.2.7 on 2021-09-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment'), ('Estate', 'Estate')], max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('bedrooms', models.IntegerField(default=1)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
    ]
